#!/usr/bin/env python3
"""Generate src/font.h (8x16 bitmap font, ASCII 32..126) from a monospace TTF.
Only needed if you want to change the font; the generated file is committed."""
import sys
from PIL import Image, ImageDraw, ImageFont
path = sys.argv[1]
size = int(sys.argv[2]) if len(sys.argv) > 2 else 13
f = ImageFont.truetype(path, size)
out = ["/* generated by tools/genfont.py - 8x16, ASCII 32..126 */",
       "static const unsigned char font8x16[95][16] = {"]
for c in range(32, 127):
    im = Image.new("1", (8, 16), 0)
    d = ImageDraw.Draw(im)
    d.fontmode = "1"
    d.text((0, -2), chr(c), font=f, fill=1)
    rows = []
    for y in range(16):
        b = 0
        for x in range(8):
            if im.getpixel((x, y)):
                b |= 0x80 >> x
        rows.append(b)
    out.append("    {" + ",".join("0x%02x" % r for r in rows) + "},")
out.append("};")
open("src/font.h", "w").write("\n".join(out) + "\n")
